### ISSUE TITLE
Incompatible ruby version on Ubuntu 18.04.3

### ISSUE THREAD

**Issue by octaviocorona** [BugSwarm/bugswarm#9]
**Update (2/11)**:
- Cannot reproduce the original issue, but facing a new issue possibly relative to Ruby `2.5.0`:

```
Encountered an error while generating the build script with travis-build: /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler/setup (LoadError)
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/oacorona/.travis/travis-build/bin/travis:27:in `<main>'.
```

**Currently unreproducible:**
Our current implementation of the `provision.sh` utilizes a command to install `ruby-full`. 
The command, `sudo apt-get --assume-yes install ruby-full` installs the correct version of Ruby (2.3.1) on Ubuntu 16.04, but will install `2.5` on Ubuntu 18.04. 

The bundler installation followed after for Travis utilizes Ruby `2.3.1` and generates a file to look for Ruby version `2.3.1`. A user with Ruby version `2.5` will have an error similar to: `.travis/travis-build/bin/travis: /usr/bin/env: 'ruby2.3': No Such file or directory`

**Comment by octaviocorona** [comment]
Migrating issue.
